<?php

namespace App\Filament\Widgets;

use App\Models\EmailBatch;
use Filament\Widgets\StatsOverviewWidget as BaseWidget;
use Filament\Widgets\StatsOverviewWidget\Stat;
use Illuminate\Support\Facades\Auth;

class UserBatchStatsOverview extends BaseWidget
{
    protected static ?int $sort = 1; // Controls the order of widgets on the dashboard

    protected function getStats(): array
    {
        $userId = Auth::id();

        $totalBatchJobs = EmailBatch::where('user_id', $userId)->count();
        $totalGeneratedEmails = EmailBatch::where('user_id', $userId)->sum('generated_count');
        $totalSentEmails = EmailBatch::where('user_id', $userId)->sum('sent_count');
        $totalFailedEmails = EmailBatch::where('user_id', $userId)->sum('failed_count');

        return [
            Stat::make('Total Batch Jobs', $totalBatchJobs)
                ->description('Your created batch jobs')
                ->descriptionIcon('heroicon-m-archive-box')
                ->color('primary'),
            Stat::make('Generated Emails', $totalGeneratedEmails)
                ->description('Total emails generated by your batches')
                ->descriptionIcon('heroicon-m-cog')
                ->color('warning'),
            Stat::make('Sent Emails', $totalSentEmails)
                ->description('Total emails successfully sent')
                ->descriptionIcon('heroicon-m-paper-airplane')
                ->color('success'),
            Stat::make('Failed Emails', $totalFailedEmails)
                ->description('Total emails that failed to send')
                ->descriptionIcon('heroicon-m-exclamation-circle')
                ->color('danger'),
        ];
    }
}
